name: Continuous integration

on:
  push:
    branches:
      - master
      - next

  pull_request:
    branches:
      - master
      - next

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.43.0", "stable", "beta", "nightly"]
    name: Check (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.43.0", "stable", "beta", "nightly"]
    name: Test Suite (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.43.0", "stable", "beta", "nightly"]
    name: Rustfmt (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }} with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["stable"]
        # rust: ["1.43.0", "stable", "beta", "nightly"]
    name: Clippy (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }} with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  website:
    runs-on: ubuntu-latest
    name: Build website
    steps:
      - uses: actions/checkout@v2
      - name: Install website dependencies
        run: yarn install
        working-directory: ./website
      - name: Build website
        run: yarn build
        working-directory: ./website
